<?php
/**
 * @var \MODX\Revolution\modX $modx
 * @var array $namespace
 */

// Include autoloader generated by your composer
require_once $namespace['path'] . 'vendor/autoload.php';

if (!$modx->services->has('activitypub')) {
    // Register base class in the service container
    $modx->services->add('activitypub', function($c) use ($modx) {
        return new \MatDave\ActivityPub\Service($modx);
    });

    // Load packages model, uncomment if you have DB tables
    $modx->addPackage('MatDave\ActivityPub\Model', $namespace['path'] . 'src/', null, 'MatDave\\ActivityPub\\');
}

// More about this file: https://docs.modx.com/3.x/en/extending-modx/namespaces#bootstrapping-services
